name: dist
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  native_build:
    strategy:
      matrix:
        os: [ "ubuntu", "windows", "macos" ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          distribution: 'graalvm-community'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew nativeCompile
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: native-${{ matrix.os }}
          path: build/native/nativeCompile

  javapackage:
    strategy:
      matrix:
        os: [ "ubuntu", "windows", "macos" ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew javapackage
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: native-${{ matrix.os }}
          path: build/javapackage

  dist:
    needs: native_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: native-ubuntu
          path: ubuntu
      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: native-windows
          path: windows
      - name: Download Macos artifact
        uses: actions/download-artifact@v2
        with:
          name: native-macos
          path: macos
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          ls windows
          ls macos
          ls ubuntu
          gh release create "$GITHUB_SHA" ubuntu/portfoward windows/portfoward.exe
