name: dist
on:
  push:
    branches: [ main ]

jobs:
  compile_and_dist:
    strategy:
      matrix:
        os: [ "ubuntu", "windows", "macos" ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          distribution: 'graalvm-community'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew nativeCompile
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: native-${{ matrix.os }}
          path: build/native
